language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - pip install .
script: cd tests && nosetests

notifications:
    email:
        on_success: never
        on_failure: always
